services:
  postgres:
    image: postgres:16
    container_name: football_sys_postgre
    restart: unless-stopped
    environment:
      POSTGRES_DB: football_sys
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: football_sys
    ports:
      - "5432:5432"
    volumes:
      - football_sys_pgdata:/var/lib/postgresql/data

volumes:
  football_sys_pgdata:
